name: Selenium Tests

on: [push, pull_request]

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    container:
      image: node:19

    services:
      selenium:
        image: selenium/standalone-chrome
        options: --shm-size=2gb

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
          cache: 'npm'
      - name: Update
        run: apt-get update

      - name: Install default-jre
        run: apt-get -y install default-jre

      - run: npm ci
      - run: npm run test
        env:
          BROWSER: ${{ github.event.inputs.browser }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshots
          path: screenshots/
